/* =============================================================
   Outward/Dispatch — script.js
   - In-browser Excel/CSV ingestion via SheetJS (no uploads)
   - Live Google Sheet sync (public CSV export + gviz fallback)
   - Data-cleaning layer for known data-entry typos
   - IndexedDB persistence (reload-safe, zero backend)
   - KPI grid, Chart.js visuals, interactive sortable matrix
   ============================================================= */
'use strict';

(function () {
  /* -------------------------------------------------------------
     Config
     ------------------------------------------------------------- */
  var SHEET_ID = '1C5JVg39Ad7gcdAJCb6qUO6qBadhm-umqRwD8CFt5oc0';
  var SHEET_CSV_URL = 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/export?format=csv';
  var SHEET_GVIZ_URL = 'https://docs.google.com/spreadsheets/d/' + SHEET_ID + '/gviz/tq?tqx=out:json&headers=1';

  /* GHMC route map (generated by ghmc-routing/generate_ghmc_route_map.py):
     maps every ward/locality -> Route Code so orders can be auto-routed from
     their Branch column even when the sheet has no Route column. */
  var GHMC_MAP_URL = 'ghmc-routing/output/ghmc_route_map.json';

  var DB_NAME = 'outward-dashboard';
  var DB_VERSION = 2;
  var STORE = 'records';
  var META_STORE = 'meta';
  var STORE_CUSTOMERS = 'customers';
  var STORE_BRANCHES = 'branches';

  var AUTO_REFRESH_MS = 300000;
  var AUTO_REFRESH_KEY = 'outward-auto-refresh';

  var REQUIRED_COLUMNS = ['Order Date', 'Customer Name', 'Branch', 'Location', 'Priority', 'Dispatch date', 'Ack'];

  /* Customer master + branch list headers → canonical field names */
  var CUSTOMER_HEADER_ALIASES = {
    'code': 'code',
    'id': 'id',
    'name': 'name',
    'type': 'type',
    'organisation': 'org',
    'organization': 'org',
    'mobile': 'mobile',
    'phone': 'mobile',
    'contact number': 'mobile',
    'gst number': 'gst',
    'gst no': 'gst',
    'gstin': 'gst',
    'dr/cr': 'drcr',
    'dr or cr': 'drcr',
    'contact person': 'contact',
    'contact': 'contact',
    'address': 'address',
    'city': 'city',
    'state': 'state',
    'pincode': 'pincode',
    'pin code': 'pincode',
    'postal code': 'pincode'
  };

  var BRANCH_HEADER_ALIASES = {
    'branch id': 'branchId',
    'branch name': 'branchName',
    'contact person': 'contact',
    'contact': 'contact',
    'mobile': 'mobile',
    'phone': 'mobile',
    'email': 'email',
    'address': 'address',
    'state': 'state',
    'pincode': 'pincode',
    'pin code': 'pincode',
    'postal code': 'pincode',
    'gst number': 'gst',
    'gst no': 'gst',
    'gstin': 'gst',
    'created at': 'createdAt',
    'created': 'createdAt'
  };

  /* Header aliases → canonical columns. Longest/most specific keys first
     so prefix-matching in the gviz fallback resolves correctly. */
  var HEADER_ALIASES = {
    'order date': 'Order Date',
    'orderdate': 'Order Date',
    'order no': 'Order Date',
    'order': 'Order Date',
    'od': 'Order Date',
    'date': 'Order Date',
    'customer name': 'Customer Name',
    'customername': 'Customer Name',
    'customer': 'Customer Name',
    'client name': 'Customer Name',
    'client': 'Customer Name',
    'branch': 'Branch',
    'branch name': 'Branch',
    'location': 'Location',
    'priority': 'Priority',
    'priority level': 'Priority',
    'dispatch date': 'Dispatch date',
    'dispatchdate': 'Dispatch date',
    'dispatch': 'Dispatch date',
    'dispatched date': 'Dispatch date',
    'despatch date': 'Dispatch date',
    'ship date': 'Dispatch date',
    'acknowledgement status': 'Ack',
    'acknowledgment status': 'Ack',
    'acknowledgement': 'Ack',
    'acknowledgment': 'Ack',
    'ack status': 'Ack',
    'ack': 'Ack',
    'route': 'Route',
    'routes': 'Route',
    'routing': 'Route'
  };

  /* Known data-entry typos → canonical place names (Hyderabad area) */
  var PLACE_TYPO_MAP = {
    'gcachibowli': 'Gachibowli',
    'gachibowli': 'Gachibowli',
    'kkatpally': 'Kukatpally',
    'kukatpally': 'Kukatpally',
    'malkpet': 'Malakpet',
    'malakpet': 'Malakpet',
    'myapur': 'Miyapur',
    'miyapur': 'Miyapur',
    'mehndipatnam': 'Mehdipatnam',
    'mehdipatnam': 'Mehdipatnam',
    'chanda nagar': 'Chandanagar',
    'chandanagar': 'Chandanagar',
    'chandanagr': 'Chandanagar',
    'hitech-city': 'Hitech City',
    'hitech city': 'Hitech City',
    'hitechcity': 'Hitech City',
    'jubileehills': 'Jubilee Hills',
    'jubilee hills': 'Jubilee Hills',
    'jublieehills': 'Jubilee Hills',
    'banjarahills': 'Banjara Hills',
    'banjara hills': 'Banjara Hills',
    'banjarahils': 'Banjara Hills',
    'panjagutta': 'Punjagutta',
    'punjagutta': 'Punjagutta',
    'lb-nagar': 'LB Nagar',
    'lb nagar': 'LB Nagar',
    'lbnagar': 'LB Nagar',
    'sr-nagar': 'SR Nagar',
    'sr nagar': 'SR Nagar',
    'srnagar': 'SR Nagar',
    'dilsukhnagar': 'Dilsukhnagar',
    'dilsuknagar': 'Dilsukhnagar',
    'himayatnagar': 'Himayatnagar',
    'himayathnagar': 'Himayatnagar',
    'kompally': 'Kompally',
    'kompalli': 'Kompally',
    'tarnaka': 'Tarnaka',
    'nizampet': 'Nizampet',
    'secunderabad': 'Secunderabad',
    'secendrabad': 'Secunderabad',
    'ameerpet': 'Ameerpet',
    'ameerpeth': 'Ameerpet',
    'begumpet': 'Begumpet',
    'kondapur': 'Kondapur',
    'madhapur': 'Madhapur',
    'madapur': 'Madhapur',
    'uppal': 'Uppal',
    'abids': 'Abids'
  };

  var PRIORITY_MAP = {
    'p1': 'P1', 'priority1': 'P1', 'high': 'P1', 'urgent': 'P1', 'top': 'P1', '1': 'P1',
    'p2': 'P2', 'priority2': 'P2', 'medium': 'P2', 'normal': 'P2', '2': 'P2',
    'p3': 'P3', 'priority3': 'P3', 'low': 'P3', '3': 'P3',
    'p4': 'P4', 'priority4': 'P4', 'none': 'P4', '4': 'P4'
  };

  var ACK_DONE = ['done', 'completed', 'complete', 'delivered', 'acked', 'acknowledged', 'ok', 'yes'];
  var ACK_TRANSIT = ['in transit', 'intransit', 'in-transit', 'transit', 'shipped', 'dispatched', 'on the way', 'inroute', 'in route', 'onroute', 'on route'];

  var PRIORITY_RANK = { 'P1': 0, 'P2': 1, 'P3': 2, 'P4': 3, '—': 4 };
  var ACK_RANK = { 'Done': 0, 'In Transit': 1, 'Pending': 2 };

  /* -------------------------------------------------------------
     State
     ------------------------------------------------------------- */
  var state = {
    records: [],
    source: null,
    customers: [],
    customersSource: null,
    branches: {},
    branchesSource: null,
    priority: 'ALL',
    ack: 'ALL',
    route: 'ALL',
    query: '',
    customerQuery: '',
    sortKey: 'orderDate',
    sortDir: 'desc',
    view: 'dispatch',
    openCustomer: null,
    dateFrom: null,
    dateTo: null,
    trendGranularity: 'month',
    barDimension: 'customer',
    autoRefresh: false,
    lastSyncAt: null
  };

  var db = null;
  var barChart = null;
  var doughnutChart = null;
  var trendChart = null;
  var agingChart = null;
  var autoRefreshTimer = null;
  var lastUpdatedTick = null;
  var syncing = false;
  var routeMap = null;

  /* -------------------------------------------------------------
     Data cleaning layer (pure — unit-testable)
     ------------------------------------------------------------- */
  function cleanPlace(v) {
    var s = String(v == null ? '' : v).trim().replace(/\s+/g, ' ');
    if (!s) return '';
    var key = s.toLowerCase();
    if (PLACE_TYPO_MAP[key]) return PLACE_TYPO_MAP[key];
    return s.split(/[\s-]+/).filter(Boolean).map(function (w) {
      if (w === w.toUpperCase()) return w;
      return w.charAt(0).toUpperCase() + w.slice(1).toLowerCase();
    }).join(' ');
  }

  function cleanCustomer(v) {
    return String(v == null ? '' : v).trim().replace(/\s+/g, ' ').replace(/\r?\n/g, ' ');
  }

  function cleanCode(v) {
    return String(v == null ? '' : v).trim();
  }

  function normalizePriority(v) {
    var key = String(v == null ? '' : v).trim().toLowerCase().replace(/\s+/g, '');
    return PRIORITY_MAP[key] || '—';
  }

  function normalizeAck(v) {
    var s = String(v == null ? '' : v).trim().toLowerCase().replace(/\s+/g, ' ');
    if (!s) return 'Pending';
    if (ACK_DONE.indexOf(s) !== -1) return 'Done';
    if (ACK_TRANSIT.indexOf(s) !== -1) return 'In Transit';
    return 'Pending';
  }

  function parseDate(v) {
    if (v == null || v === '') return null;
    if (v instanceof Date) return isNaN(v.getTime()) ? null : v;
    if (typeof v === 'number' && isFinite(v)) {
      if (typeof XLSX !== 'undefined' && XLSX.SSF && XLSX.SSF.parse_date_code) {
        var d = XLSX.SSF.parse_date_code(v);
        if (d) return new Date(d.y, d.m - 1, d.d);
      }
      return null;
    }
    var s = String(v).trim();
    if (!s) return null;

    var gviz = s.match(/^Date\((\d{4}),(\d{1,2}),(\d{1,2})\)$/);
    if (gviz) return new Date(+gviz[1], +gviz[2], +gviz[3]);

    /* dd/mm/yyyy (dataset format) — defensively swap if month>12 */
    var sl = s.match(/^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{2,4})$/);
    if (sl) {
      var day = +sl[1], mon = +sl[2], yr = +sl[3];
      if (yr < 100) yr += 2000;
      if (mon > 12 && day <= 12) {
        var t = day; day = mon; mon = t;
      }
      if (mon >= 1 && mon <= 12 && day >= 1 && day <= 31) {
        var dt = new Date(yr, mon - 1, day);
        return isNaN(dt.getTime()) ? null : dt;
      }
      return null;
    }

    var iso = new Date(s);
    return isNaN(iso.getTime()) ? null : iso;
  }

  function normalizeRecord(raw) {
    return {
      id: makeId(),
      orderDate: parseDate(raw['Order Date']),
      customer: cleanCustomer(raw['Customer Name']),
      branch: cleanPlace(raw['Branch']),
      location: cleanPlace(raw['Location']),
      priority: normalizePriority(raw['Priority']),
      dispatchDate: parseDate(raw['Dispatch date']),
      ack: normalizeAck(raw['Ack']),
      route: cleanCode(raw['Route'])
    };
  }

  function makeId() {
    if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID();
    return 'r-' + Date.now().toString(36) + '-' + Math.random().toString(36).slice(2, 10);
  }

  /* -------------------------------------------------------------
     GHMC route map → Route Code lookup (auto-route orders from Branch)
     ------------------------------------------------------------- */
  function routeNameSlug(v) {
    return String(v == null ? '' : v).toLowerCase().replace(/[^a-z0-9]/g, '');
  }

  function buildRouteIndex(mapRecords) {
    var idx = {};
    var add = function (name, route) {
      var slug = routeNameSlug(name);
      if (slug && !(slug in idx)) idx[slug] = route;
    };
    (mapRecords || []).forEach(function (rec) {
      var raw = rec['GHMC Ward Number & Name'];
      if (raw == null) return;
      var s = String(raw).trim();
      var names;
      if (s.indexOf('- (') === 0) {
        names = s.split(':').slice(1).join(':').trim()
          .split(',').map(function (x) { return x.trim(); });
      } else {
        var m = s.match(/^\s*\d+\s*-\s*(.+)$/);
        names = [m ? m[1].trim() : s];
      }
      names.forEach(function (name) { add(name, rec['Route Code']); });
      add(rec['GHMC Circle Name'], rec['Route Code']);
    });
    return idx;
  }

  function routeFromBranch(branch, idx) {
    idx = idx || routeMap;
    if (!idx) return '';
    var slug = routeNameSlug(cleanPlace(branch));
    return slug && idx[slug] ? idx[slug] : '';
  }

  function enrichRoutes(records, idx) {
    idx = idx || routeMap;
    if (!idx) return records;
    for (var i = 0; i < records.length; i++) {
      if (!records[i].route) records[i].route = routeFromBranch(records[i].branch, idx) || '';
    }
    return records;
  }

  /* -------------------------------------------------------------
     Workbook → records (header-tolerant, error-bounded)
     ------------------------------------------------------------- */
  function normHeaderKey(v) {
    return String(v == null ? '' : v)
      .toLowerCase()
      .replace(/[-_.]/g, ' ')
      .replace(/[()[\]]/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();
  }

  function detectHeaders(rows) {
    var headerMap = {};
    var startIndex = 0;
    for (var i = 0; i < rows.length; i++) {
      var row = rows[i];
      if (!row || !row.some(function (c) { return String(c == null ? '' : c).trim() !== ''; })) {
        startIndex = i + 1;
        continue;
      }
      row.forEach(function (cell, colIdx) {
        var key = normHeaderKey(cell);
        if (HEADER_ALIASES[key] && !(HEADER_ALIASES[key] in headerMap)) {
          headerMap[HEADER_ALIASES[key]] = colIdx;
        }
      });
      startIndex = i + 1;
      break;
    }
    var missing = REQUIRED_COLUMNS.filter(function (c) { return !(c in headerMap); });
    return { headerMap: headerMap, missing: missing, startIndex: startIndex };
  }

  function buildRecords(rows, headerMap, startIndex) {
    var records = [];
    for (var i = startIndex; i < rows.length; i++) {
      var row = rows[i];
      if (!row || !row.some(function (c) { return String(c == null ? '' : c).trim() !== ''; })) continue;
      var raw = {};
      for (var canon in headerMap) raw[canon] = row[headerMap[canon]] == null ? '' : row[headerMap[canon]];
      var rec = normalizeRecord(raw);
      if (!rec.customer && !rec.branch && !rec.location) continue;
      records.push(rec);
    }
    return records;
  }

  function ingestWorkbook(wb) {
    var allRows = [];
    for (var i = 0; i < wb.SheetNames.length; i++) {
      var sheet = wb.Sheets[wb.SheetNames[i]];
      if (!sheet || !sheet['!ref']) continue;
      allRows = allRows.concat(XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '', raw: true }));
    }
    var detection = detectHeaders(allRows);
    if (detection.missing.length) return { records: [], missing: detection.missing };
    return { records: buildRecords(allRows, detection.headerMap, detection.startIndex), missing: [] };
  }

  /* -------------------------------------------------------------
     Customer master + branch workbook parsing
     ------------------------------------------------------------- */
  function findHeaderRow(rows) {
    for (var i = 0; i < rows.length; i++) {
      var row = rows[i];
      if (!row) continue;
      for (var j = 0; j < row.length; j++) {
        if (String(row[j] == null ? '' : row[j]).trim() !== '') return i;
      }
    }
    return -1;
  }

  /* Classify a workbook as 'dispatch', 'customers', 'branches' or null */
  function classifyWorkbook(rows) {
    var hr = findHeaderRow(rows);
    if (hr === -1) return null;
    var keys = {};
    rows[hr].forEach(function (cell) {
      var k = normHeaderKey(cell);
      if (k) keys[k] = true;
    });
    if (keys['branch id'] && keys['branch name']) return 'branches';
    if (keys['code'] && keys['name'] && (keys['gst number'] || keys['gst no'])) return 'customers';
    var detection = detectHeaders(rows);
    return detection.missing.length ? null : 'dispatch';
  }

  function codeFromFilename(name) {
    var stem = String(name == null ? '' : name).replace(/\.(xlsx|xls|csv)$/i, '').trim();
    var cl = stem.match(/(CL-\d{6}-\d{4})/i);
    if (cl) return cl[1].toUpperCase();
    var c = stem.match(/(C\d{3,})/i);
    if (c) return c[1].toUpperCase();
    return stem.toUpperCase();
  }

  function parseCustomerMaster(rows) {
    var hr = findHeaderRow(rows);
    if (hr === -1) return [];
    var map = {};
    rows[hr].forEach(function (cell, idx) {
      var k = CUSTOMER_HEADER_ALIASES[normHeaderKey(cell)];
      if (k && !(k in map)) map[k] = idx;
    });
    var out = [];
    for (var i = hr + 1; i < rows.length; i++) {
      var row = rows[i];
      if (!row || !row.some(function (c) { return String(c == null ? '' : c).trim() !== ''; })) continue;
      var code = cleanCode(row[map['code']]);
      var name = cleanCustomer(row[map['name']]);
      if (!code && !name) continue;
      out.push({
        code: code,
        id: cleanCode(row[map['id']]),
        name: name,
        type: cleanCustomer(row[map['type']]),
        org: cleanCustomer(row[map['org']]),
        mobile: cleanCode(row[map['mobile']]),
        gst: cleanCode(row[map['gst']]),
        drcr: cleanCustomer(row[map['drcr']]),
        contact: cleanCustomer(row[map['contact']]),
        address: cleanCustomer(row[map['address']]),
        city: cleanPlace(row[map['city']]),
        state: cleanCustomer(row[map['state']]),
        pincode: cleanCode(row[map['pincode']])
      });
    }
    return out;
  }

  function parseBranchList(rows) {
    var hr = findHeaderRow(rows);
    if (hr === -1) return [];
    var map = {};
    rows[hr].forEach(function (cell, idx) {
      var k = BRANCH_HEADER_ALIASES[normHeaderKey(cell)];
      if (k && !(k in map)) map[k] = idx;
    });
    var out = [];
    for (var i = hr + 1; i < rows.length; i++) {
      var row = rows[i];
      if (!row || !row.some(function (c) { return String(c == null ? '' : c).trim() !== ''; })) continue;
      out.push({
        branchId: cleanCode(row[map['branchId']]),
        branchName: cleanCustomer(row[map['branchName']]),
        contact: cleanCustomer(row[map['contact']]),
        mobile: cleanCode(row[map['mobile']]),
        email: cleanCustomer(row[map['email']]),
        address: cleanCustomer(row[map['address']]),
        state: cleanCustomer(row[map['state']]),
        pincode: cleanCode(row[map['pincode']]),
        gst: cleanCode(row[map['gst']]),
        createdAt: cleanCustomer(row[map['createdAt']])
      });
    }
    return out;
  }

  /* gviz JSON fallback for the live sheet (best effort) */
  function parseGvizRows(text) {
    var json;
    try {
      var body = String(text).trim();
      body = body.replace(/^\/\*O_o\*\//, '');
      body = body.slice(body.indexOf('(') + 1);
      body = body.replace(/\);?\s*$/, '');
      json = JSON.parse(body);
    } catch (e) {
      throw new Error('Could not parse the Google Sheet response.');
    }
    if (!json || !json.table) throw new Error('Google Sheet returned no table.');
    var cols = json.table.cols || [];
    var rows = json.table.rows || [];
    var headerIdx = {};
    var aliasKeys = Object.keys(HEADER_ALIASES);
    cols.forEach(function (col, i) {
      var label = col && col.label ? String(col.label) : '';
      var norm = label.toLowerCase();
      var canonical = HEADER_ALIASES[norm];
      if (!canonical) {
        for (var a = 0; a < aliasKeys.length; a++) {
          if (norm.indexOf(aliasKeys[a]) === 0) {
            canonical = HEADER_ALIASES[aliasKeys[a]];
            break;
          }
        }
      }
      if (canonical && !(canonical in headerIdx)) headerIdx[canonical] = i;
    });
    var missing = REQUIRED_COLUMNS.filter(function (c) { return !(c in headerIdx); });
    if (missing.length) throw new Error('Required columns missing: ' + missing.join(', '));
    return rows.filter(function (r) { return r && r.c; }).map(function (r) {
      var raw = {};
      for (var canon in headerIdx) {
        var cell = r.c[headerIdx[canon]];
        var val = '';
        if (cell) {
          if (cell.f != null) val = cell.f;
          else if (Array.isArray(cell.v)) val = cell.v.join(', ');
          else val = cell.v;
        }
        raw[canon] = val == null ? '' : val;
      }
      return raw;
    });
  }

  /* -------------------------------------------------------------
     Derived computations
     ------------------------------------------------------------- */
  function computeKpis(rows) {
    var total = rows.length;
    var bottlenecks = 0, done = 0, transit = 0, pending = 0, days = 0, velocityCount = 0;
    for (var i = 0; i < rows.length; i++) {
      var r = rows[i];
      if (r.priority === 'P1' && r.ack !== 'Done') bottlenecks++;
      if (r.ack === 'Done') done++;
      else if (r.ack === 'In Transit') transit++;
      else pending++;
      if (r.orderDate && r.dispatchDate) {
        var diff = (r.dispatchDate.getTime() - r.orderDate.getTime()) / 86400000;
        if (diff >= 0) { days += diff; velocityCount++; }
      }
    }
    return {
      total: total,
      bottlenecks: bottlenecks,
      done: done,
      transit: transit,
      pending: pending,
      velocity: velocityCount ? days / velocityCount : 0,
      velocityCount: velocityCount,
      fulfillment: total ? (done / total) * 100 : 0
    };
  }

  function buildBarData(rows, dimension) {
    var dim = dimension || 'customer';
    var counts = {};
    rows.forEach(function (r) {
      var c;
      if (dim === 'location') c = r.location || 'Unknown';
      else if (dim === 'branch') c = r.branch || 'Unknown';
      else c = r.customer || 'Unknown';
      counts[c] = (counts[c] || 0) + 1;
    });
    var entries = Object.keys(counts).map(function (k) { return [k, counts[k]]; })
      .sort(function (a, b) { return b[1] - a[1]; });
    var top = entries.slice(0, 12);
    var labels = top.map(function (e) { return e[0]; });
    var data = top.map(function (e) { return e[1]; });
    var rest = entries.slice(12).reduce(function (sum, e) { return sum + e[1]; }, 0);
    if (rest > 0) { labels.push('Others'); data.push(rest); }
    return { labels: labels, data: data };
  }

  function buildDoughnutData(rows) {
    var k = computeKpis(rows);
    return { labels: ['Done', 'In Transit', 'Pending'], data: [k.done, k.transit, k.pending], total: k.total };
  }

  function pad2(n) { return n < 10 ? '0' + n : '' + n; }

  function startOfDay(d) { return new Date(d.getFullYear(), d.getMonth(), d.getDate()); }

  function startOfWeek(d) {
    var day = (d.getDay() + 6) % 7;
    var s = startOfDay(d);
    s.setDate(s.getDate() - day);
    return s;
  }

  function startOfMonth(d) { return new Date(d.getFullYear(), d.getMonth(), 1); }

  function buildTrendData(rows, granularity) {
    var g = granularity || 'month';
    var buckets = {};
    function add(key, count) { buckets[key] = (buckets[key] || 0) + count; }
    rows.forEach(function (r) {
      var oKey = null, dKey = null;
      if (r.orderDate) {
        var os = g === 'day' ? startOfDay(r.orderDate) : (g === 'week' ? startOfWeek(r.orderDate) : startOfMonth(r.orderDate));
        oKey = os.getTime();
        if (buckets[oKey] == null) buckets[oKey] = { key: os, orders: 0, dispatched: 0 };
        buckets[oKey].orders++;
      }
      if (r.dispatchDate) {
        var ds = g === 'day' ? startOfDay(r.dispatchDate) : (g === 'week' ? startOfWeek(r.dispatchDate) : startOfMonth(r.dispatchDate));
        dKey = ds.getTime();
        if (buckets[dKey] == null) buckets[dKey] = { key: ds, orders: 0, dispatched: 0 };
        buckets[dKey].dispatched++;
      }
    });
    var keys = Object.keys(buckets).map(Number).sort(function (a, b) { return a - b; });
    var labels = [], orders = [], dispatched = [];
    for (var i = 0; i < keys.length; i++) {
      var b = buckets[keys[i]];
      labels.push(b.key.toLocaleDateString(undefined, g === 'month'
        ? { month: 'short', year: '2-digit' }
        : { month: 'short', day: 'numeric' }));
      orders.push(b.orders);
      dispatched.push(b.dispatched);
    }
    return { labels: labels, orders: orders, dispatched: dispatched };
  }

  function buildRouteStats(rows) {
    var map = {};
    rows.forEach(function (r) {
      var key = r.route || '';
      if (!key) return;
      if (!map[key]) map[key] = { route: key, total: 0, done: 0, transit: 0, pending: 0, openP1: 0 };
      var s = map[key];
      s.total++;
      if (r.ack === 'Done') s.done++;
      else if (r.ack === 'In Transit') s.transit++;
      else s.pending++;
      if (r.priority === 'P1' && r.ack !== 'Done') s.openP1++;
    });
    var list = Object.keys(map).map(function (k) { return map[k]; })
      .sort(function (a, b) {
        return b.total - a.total || String(a.route).localeCompare(String(b.route), undefined, { numeric: true });
      });
    list.forEach(function (s) {
      s.fulfillment = s.total ? (s.done / s.total) * 100 : 0;
    });
    return list;
  }

  var AGING_BUCKETS = [
    { key: '0-3d', label: '0–3 days', min: 0, max: 3 },
    { key: '4-7d', label: '4–7 days', min: 4, max: 7 },
    { key: '8-14d', label: '8–14 days', min: 8, max: 14 },
    { key: '15-30d', label: '15–30 days', min: 15, max: 30 },
    { key: '31d+', label: '31+ days', min: 31, max: Infinity }
  ];

  function buildAgingData(rows, now) {
    var today = now ? new Date(now.getTime()) : new Date();
    today.setHours(0, 0, 0, 0);
    var buckets = AGING_BUCKETS.map(function (b) { return { key: b.key, label: b.label, count: 0 }; });
    var open = [];
    rows.forEach(function (r) {
      if (r.priority !== 'P1' || r.ack === 'Done' || !r.orderDate) return;
      var start = new Date(r.orderDate);
      start.setHours(0, 0, 0, 0);
      var age = Math.floor((today.getTime() - start.getTime()) / 86400000);
      if (age < 0) age = 0;
      for (var j = 0; j < AGING_BUCKETS.length; j++) {
        if (age >= AGING_BUCKETS[j].min && age <= AGING_BUCKETS[j].max) {
          buckets[j].count++;
          break;
        }
      }
      open.push({ age: age, customer: r.customer, branch: r.branch, location: r.location, orderDate: r.orderDate, ack: r.ack });
    });
    open.sort(function (a, b) { return b.age - a.age; });
    return { total: open.length, buckets: buckets, oldest: open.slice(0, 10) };
  }

  function auditData(records) {
    var cats = [
      { key: 'noOrderDate', label: 'Missing order date', rows: [] },
      { key: 'noDispatchDate', label: 'Missing dispatch date', rows: [] },
      { key: 'noCustomer', label: 'Missing customer name', rows: [] },
      { key: 'noBranch', label: 'Missing branch', rows: [] },
      { key: 'noPriority', label: 'Unrecognised priority', rows: [] },
      { key: 'dispatchBeforeOrder', label: 'Dispatch before order date', rows: [] },
      { key: 'futureOrder', label: 'Future-dated orders', rows: [] }
    ];
    var today = new Date();
    today.setHours(0, 0, 0, 0);
    records.forEach(function (r) {
      if (!r.orderDate) cats[0].rows.push(r);
      if (!r.dispatchDate) cats[1].rows.push(r);
      if (!r.customer) cats[2].rows.push(r);
      if (!r.branch) cats[3].rows.push(r);
      if (r.priority === '—') cats[4].rows.push(r);
      if (r.orderDate && r.dispatchDate && r.dispatchDate.getTime() < r.orderDate.getTime()) cats[5].rows.push(r);
      if (r.orderDate && r.orderDate.getTime() > today.getTime() + 86400000) cats[6].rows.push(r);
    });
    var issues = cats
      .filter(function (c) { return c.rows.length > 0; })
      .map(function (c) { return { key: c.key, label: c.label, count: c.rows.length, rows: c.rows.slice(0, 10) }; })
      .sort(function (a, b) { return b.count - a.count; });
    return { total: records.length, issues: issues };
  }

  function customerOrderStats(customerName, records) {
    var needle = cleanCustomer(customerName).toLowerCase();
    var orders = 0, open = 0;
    for (var i = 0; i < records.length; i++) {
      if (records[i].customer.toLowerCase() === needle) {
        orders++;
        if (records[i].ack !== 'Done') open++;
      }
    }
    return { orders: orders, open: open };
  }

  function filteredRows(ignoreRoute) {
    var rows = state.records;
    if (state.priority !== 'ALL') rows = rows.filter(function (r) { return r.priority === state.priority; });
    if (state.ack !== 'ALL') rows = rows.filter(function (r) { return r.ack === state.ack; });
    if (!ignoreRoute && state.route !== 'ALL') rows = rows.filter(function (r) { return r.route === state.route; });
    if (state.dateFrom) {
      var from = new Date(state.dateFrom);
      rows = rows.filter(function (r) { return r.orderDate && r.orderDate.getTime() >= from.getTime(); });
    }
    if (state.dateTo) {
      var to = new Date(state.dateTo);
      to.setHours(23, 59, 59, 999);
      rows = rows.filter(function (r) { return r.orderDate && r.orderDate.getTime() <= to.getTime(); });
    }
    if (state.query) {
      var q = state.query.toLowerCase();
      rows = rows.filter(function (r) {
        return r.customer.toLowerCase().indexOf(q) !== -1 ||
          r.branch.toLowerCase().indexOf(q) !== -1 ||
          r.location.toLowerCase().indexOf(q) !== -1 ||
          (r.route || '').toLowerCase().indexOf(q) !== -1;
      });
    }
    return rows;
  }

  function sortRows(rows, key, dir) {
    var mul = dir === 'asc' ? 1 : -1;
    return rows.slice().sort(function (a, b) {
      var cmp = 0;
      if (key === 'orderDate' || key === 'dispatchDate') {
        var av = a[key] ? a[key].getTime() : Infinity;
        var bv = b[key] ? b[key].getTime() : Infinity;
        cmp = av === bv ? 0 : (av < bv ? -1 : 1);
      } else if (key === 'priority') {
        cmp = (PRIORITY_RANK[a.priority] != null ? PRIORITY_RANK[a.priority] : 4) -
              (PRIORITY_RANK[b.priority] != null ? PRIORITY_RANK[b.priority] : 4);
      } else if (key === 'ack') {
        cmp = (ACK_RANK[a.ack] != null ? ACK_RANK[a.ack] : 2) -
              (ACK_RANK[b.ack] != null ? ACK_RANK[b.ack] : 2);
      } else {
        cmp = String(a[key] == null ? '' : a[key]).localeCompare(
          String(b[key] == null ? '' : b[key]), undefined, { numeric: true, sensitivity: 'base' });
      }
      return cmp * mul;
    });
  }

  /* -------------------------------------------------------------
     IndexedDB persistence
     ------------------------------------------------------------- */
  function openDB() {
    return new Promise(function (resolve) {
      if (typeof indexedDB === 'undefined') { resolve(null); return; }
      try {
        var req = indexedDB.open(DB_NAME, DB_VERSION);
        req.onupgradeneeded = function (e) {
          var d = e.target.result;
          if (!d.objectStoreNames.contains(STORE)) d.createObjectStore(STORE, { keyPath: 'id' });
          if (!d.objectStoreNames.contains(META_STORE)) d.createObjectStore(META_STORE, { keyPath: 'key' });
          if (!d.objectStoreNames.contains(STORE_CUSTOMERS)) d.createObjectStore(STORE_CUSTOMERS, { keyPath: 'code' });
          if (!d.objectStoreNames.contains(STORE_BRANCHES)) d.createObjectStore(STORE_BRANCHES, { keyPath: 'code' });
        };
        req.onsuccess = function () { resolve(req.result); };
        req.onerror = function () { console.warn('IndexedDB open failed:', req.error); resolve(null); };
        req.onblocked = function () { resolve(null); };
      } catch (e) {
        console.warn('IndexedDB unavailable:', e);
        resolve(null);
      }
    });
  }

  function txDone(tx) {
    return new Promise(function (resolve, reject) {
      tx.oncomplete = resolve;
      tx.onerror = function () { reject(tx.error); };
      tx.onabort = function () { reject(tx.error); };
    });
  }

  function persistRecords(records, source) {
    if (!db) return Promise.resolve();
    return new Promise(function (resolve, reject) {
      try {
        var tx = db.transaction([STORE, META_STORE], 'readwrite');
        tx.objectStore(STORE).clear();
        for (var i = 0; i < records.length; i++) tx.objectStore(STORE).put(records[i]);
        tx.objectStore(META_STORE).put({
          key: 'source',
          name: source ? source.name : null,
          syncedAt: source && source.syncedAt ? source.syncedAt : Date.now()
        });
        txDone(tx).then(resolve, reject);
      } catch (e) {
        console.warn('IndexedDB write failed:', e);
        reject(e);
      }
    });
  }

  function persistCustomers(customers, source) {
    if (!db) return Promise.resolve();
    return new Promise(function (resolve, reject) {
      try {
        var tx = db.transaction([STORE_CUSTOMERS, META_STORE], 'readwrite');
        tx.objectStore(STORE_CUSTOMERS).clear();
        for (var i = 0; i < customers.length; i++) tx.objectStore(STORE_CUSTOMERS).put(customers[i]);
        tx.objectStore(META_STORE).put({
          key: 'customers_source',
          name: source ? source.name : null,
          syncedAt: source && source.syncedAt ? source.syncedAt : Date.now()
        });
        txDone(tx).then(resolve, reject);
      } catch (e) {
        console.warn('IndexedDB write failed:', e);
        reject(e);
      }
    });
  }

  function persistBranches(branchesMap, source) {
    if (!db) return Promise.resolve();
    return new Promise(function (resolve, reject) {
      try {
        var tx = db.transaction([STORE_BRANCHES, META_STORE], 'readwrite');
        tx.objectStore(STORE_BRANCHES).clear();
        var codes = Object.keys(branchesMap);
        for (var i = 0; i < codes.length; i++) {
          tx.objectStore(STORE_BRANCHES).put({ code: codes[i], list: branchesMap[codes[i]] });
        }
        tx.objectStore(META_STORE).put({
          key: 'branches_source',
          name: source ? source.name : null,
          syncedAt: source && source.syncedAt ? source.syncedAt : Date.now()
        });
        txDone(tx).then(resolve, reject);
      } catch (e) {
        console.warn('IndexedDB write failed:', e);
        reject(e);
      }
    });
  }

  function loadPersisted() {
    if (!db) return Promise.resolve(null);
    return new Promise(function (resolve) {
      try {
        var tx = db.transaction([STORE, META_STORE, STORE_CUSTOMERS, STORE_BRANCHES], 'readonly');
        var recsReq = tx.objectStore(STORE).getAll();
        var metaReq = tx.objectStore(META_STORE).get('source');
        var custReq = tx.objectStore(STORE_CUSTOMERS).getAll();
        var custMetaReq = tx.objectStore(META_STORE).get('customers_source');
        var brReq = tx.objectStore(STORE_BRANCHES).getAll();
        var brMetaReq = tx.objectStore(META_STORE).get('branches_source');
        txDone(tx).then(function () {
          resolve({
            records: recsReq.result || [],
            meta: metaReq.result || null,
            customers: custReq.result || [],
            customersMeta: custMetaReq.result || null,
            branches: brReq.result || [],
            branchesMeta: brMetaReq.result || null
          });
        }, function (e) {
          console.warn('IndexedDB read failed:', e);
          resolve(null);
        });
      } catch (e) {
        console.warn('IndexedDB read failed:', e);
        resolve(null);
      }
    });
  }

  /* -------------------------------------------------------------
     Rendering helpers
     ------------------------------------------------------------- */
  function $(id) { return document.getElementById(id); }

  function setText(id, value) {
    var el = $(id);
    if (el) el.textContent = value;
  }

  function formatNum(n) { return Number(n || 0).toLocaleString('en-IN'); }

  function formatDate(d) {
    if (!d) return '<span class="pending-date">—</span>';
    var dd = String(d.getDate()).padStart(2, '0');
    var mm = String(d.getMonth() + 1).padStart(2, '0');
    return dd + '/' + mm + '/' + d.getFullYear();
  }

  function escapeHtml(s) {
    return String(s).replace(/[&<>"']/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
    });
  }

  function isFileProtocol() {
    return typeof location !== 'undefined' && location.protocol === 'file:';
  }

  function refreshIcons() {
    if (typeof lucide !== 'undefined' && lucide.createIcons) {
      try { lucide.createIcons(); } catch (e) { /* no-op */ }
    }
  }

  function setChartEmpty(id, show) {
    var el = $(id);
    if (el) el.hidden = !show;
    refreshIcons();
  }

  function toast(message, type, timeout) {
    type = type || 'info';
    timeout = timeout || 4200;
    var stack = $('toastStack');
    if (!stack) return;
    var el = document.createElement('div');
    el.className = 'toast toast-' + type;
    var icon = type === 'success' ? 'check-circle-2' : (type === 'error' ? 'alert-triangle' : 'info');
    el.innerHTML = '<i data-lucide="' + icon + '"></i><span></span>';
    el.querySelector('span').textContent = message;
    stack.appendChild(el);
    refreshIcons();
    setTimeout(function () {
      el.classList.add('toast-out');
      setTimeout(function () { if (el.parentNode) el.parentNode.removeChild(el); }, 220);
    }, timeout);
  }

  function showError(message) {
    var banner = $('errorBanner');
    if (banner) {
      banner.innerHTML =
        '<i data-lucide="alert-triangle"></i>' +
        '<span></span>' +
        '<button type="button" class="error-close" aria-label="Dismiss"><i data-lucide="x"></i></button>';
      banner.querySelector('span').textContent = message;
      banner.hidden = false;
      banner.querySelector('.error-close').addEventListener('click', function () { banner.hidden = true; });
      refreshIcons();
      if (banner.scrollIntoView) banner.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
    toast(message, 'error');
  }

  var LOCAL_NOTICE_MSG =
    'Google Sheets sync is blocked when this page is opened directly from the file system. ' +
    'Run "npx serve" (or "python -m http.server") in this folder and open it via http:// — ' +
    'or simply drag & drop the Excel/CSV export here.';

  function showLocalNotice() {
    var el = $('localNotice');
    if (!el || el.hidden === false) return;
    var span = el.querySelector('span');
    if (span) span.textContent = LOCAL_NOTICE_MSG;
    el.hidden = false;
    refreshIcons();
    var close = el.querySelector('.error-close');
    if (close) close.addEventListener('click', function () { el.hidden = true; });
  }

  function describeSyncError(err) {
    if (isFileProtocol()) {
      return 'Google Sheets blocks data access for pages opened from the file system. ' +
        'Serve this folder over HTTP ("npx serve" or "python -m http.server"), then reopen — ' +
        'or drag & drop the Excel/CSV export directly into the drop zone.';
    }
    if (err && err.message === 'Failed to fetch') {
      return 'Could not reach Google Sheets — usually a network issue or an ad/tracker blocker. ' +
        'Check your connection, disable browser extensions for this page, and try again.';
    }
    return err && err.message ? err.message : 'Unknown error.';
  }

  function priorityBadge(p) {
    var clsMap = { P1: 'badge-p1', P2: 'badge-p2', P3: 'badge-p3', P4: 'badge-p4' };
    var dotMap = { P1: 'dot-p1', P2: 'dot-p2', P3: 'dot-p3', P4: 'dot-p4' };
    var cls = clsMap[p] || 'badge-neutral';
    var dot = dotMap[p] || 'dot-p4';
    return '<span class="badge ' + cls + '"><span class="dot ' + dot + '"></span>' + escapeHtml(p) + '</span>';
  }

  function ackBadge(a) {
    var clsMap = { 'Done': 'badge-done', 'In Transit': 'badge-transit', 'Pending': 'badge-pending' };
    var dotMap = { 'Done': 'dot-done', 'In Transit': 'dot-transit', 'Pending': 'dot-pending' };
    var cls = clsMap[a] || 'badge-neutral';
    var dot = dotMap[a] || 'dot-pending';
    return '<span class="badge ' + cls + '"><span class="dot ' + dot + '"></span>' + escapeHtml(a) + '</span>';
  }

  /* -------------------------------------------------------------
     KPI grid
     ------------------------------------------------------------- */
  function renderKpis(rows) {
    var k = computeKpis(rows);
    var scope = rows.length === state.records.length;
    setText('kpiVolume', formatNum(k.total));
    setText('kpiVolumeNote', scope ? 'records in scope' : formatNum(k.total) + ' of ' + formatNum(state.records.length) + ' in scope');
    setText('kpiBottleneck', formatNum(k.bottlenecks));
    setText('kpiVelocity', k.velocityCount ? k.velocity.toFixed(1) + 'd' : '—');
    setText('kpiFulfillment', k.total ? k.fulfillment.toFixed(1) + '%' : '—');
  }

  /* -------------------------------------------------------------
     Charts
     ------------------------------------------------------------- */
  var centerTextPlugin = {
    id: 'centerText',
    afterDraw: function (chart, args, opts) {
      if (!opts || !opts.total || !chart.data || !chart.data.datasets.length) return;
      var dataset = chart.data.datasets[0];
      if (!dataset || !dataset.data || !dataset.data.length) return;
      var meta = chart.getDatasetMeta(0);
      if (!meta.data || !meta.data.length) return;
      var point = meta.data[0];
      var x = point ? point.x : chart.width / 2;
      var y = point ? point.y : chart.height / 2;
      var ctx = chart.ctx;
      ctx.save();
      ctx.textAlign = 'center';
      ctx.textBaseline = 'middle';
      ctx.font = "600 24px 'Inter', sans-serif";
      ctx.fillStyle = '#1a1d21';
      ctx.fillText(Number(opts.total).toLocaleString('en-IN'), x, y - 7);
      ctx.font = "400 11px 'Inter', sans-serif";
      ctx.fillStyle = '#6b7078';
      ctx.fillText('records', x, y + 12);
      ctx.restore();
    }
  };

  function createCharts() {
    if (typeof Chart === 'undefined') {
      showError('Chart.js failed to load — check your internet connection and reload.');
      return;
    }
    Chart.defaults.font.family = "'Inter', system-ui, sans-serif";
    Chart.defaults.font.size = 12;
    Chart.defaults.animation.duration = 350;

    var barCtx = $('barChart');
    if (barCtx) {
      barChart = new Chart(barCtx, {
        type: 'bar',
        data: {
          labels: [],
          datasets: [{
            data: [],
            backgroundColor: '#5e6ad2',
            hoverBackgroundColor: '#828fff',
            borderRadius: 5,
            borderSkipped: false,
            maxBarThickness: 20
          }]
        },
        options: {
          indexAxis: 'y',
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false },
            tooltip: {
              backgroundColor: '#ffffff',
              borderColor: '#e5e8ec',
              borderWidth: 1,
              titleColor: '#1a1d21',
              bodyColor: '#3f454d',
              padding: 10,
              cornerRadius: 8,
              displayColors: false
            }
          },
          scales: {
            x: {
              beginAtZero: true,
              grid: { color: '#eceff3' },
              border: { color: '#d4d8de' },
              ticks: { color: '#6b7078', precision: 0, callback: function (v) { return Number(v).toLocaleString('en-IN'); } }
            },
            y: {
              grid: { display: false },
              border: { color: '#d4d8de' },
              ticks: { color: '#3f454d', autoSkip: false, font: { size: 12 } }
            }
          }
        }
      });
    }

    var doughnutCtx = $('doughnutChart');
    if (doughnutCtx) {
      doughnutChart = new Chart(doughnutCtx, {
        type: 'doughnut',
        data: {
          labels: ['Done', 'In Transit', 'Pending'],
          datasets: [{
            data: [],
            backgroundColor: ['#27a644', '#4aa8ff', '#f59e0b'],
            borderColor: '#ffffff',
            borderWidth: 4,
            hoverOffset: 8
          }]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          cutout: '68%',
          plugins: {
            centerText: { total: 0 },
            legend: {
              position: 'bottom',
              labels: { color: '#3f454d', usePointStyle: true, pointStyle: 'circle', boxWidth: 8, padding: 18 }
            },
            tooltip: {
              backgroundColor: '#ffffff',
              borderColor: '#e5e8ec',
              borderWidth: 1,
              titleColor: '#1a1d21',
              bodyColor: '#3f454d',
              padding: 10,
              cornerRadius: 8
            }
          }
        },
        plugins: [centerTextPlugin]
      });
    }

    var trendCtx = $('trendChart');
    if (trendCtx) {
      trendChart = new Chart(trendCtx, {
        type: 'line',
        data: {
          labels: [],
          datasets: [
            {
              label: 'Orders',
              data: [],
              borderColor: '#5e6ad2',
              backgroundColor: 'rgba(94, 106, 210, 0.10)',
              fill: true,
              tension: 0.35,
              pointRadius: 2,
              pointHoverRadius: 4,
              borderWidth: 2
            },
            {
              label: 'Dispatched',
              data: [],
              borderColor: '#27a644',
              backgroundColor: 'rgba(39, 166, 68, 0.05)',
              fill: false,
              tension: 0.35,
              pointRadius: 2,
              pointHoverRadius: 4,
              borderWidth: 2
            }
          ]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          interaction: { mode: 'index', intersect: false },
          plugins: {
            legend: { labels: { color: '#3f454d', usePointStyle: true, pointStyle: 'circle', boxWidth: 8, padding: 16 } },
            tooltip: {
              backgroundColor: '#ffffff',
              borderColor: '#e5e8ec',
              borderWidth: 1,
              titleColor: '#1a1d21',
              bodyColor: '#3f454d',
              padding: 10,
              cornerRadius: 8
            }
          },
          scales: {
            x: {
              grid: { display: false },
              border: { color: '#d4d8de' },
              ticks: { color: '#6b7078', maxTicksLimit: 12, maxRotation: 45 }
            },
            y: {
              beginAtZero: true,
              grid: { color: '#eceff3' },
              border: { color: '#d4d8de' },
              ticks: { color: '#6b7078', precision: 0, callback: function (v) { return Number(v).toLocaleString('en-IN'); } }
            }
          }
        }
      });
    }

    var agingCtx = $('agingChart');
    if (agingCtx) {
      agingChart = new Chart(agingCtx, {
        type: 'bar',
        data: {
          labels: [],
          datasets: [{
            data: [],
            backgroundColor: '#f5a623',
            hoverBackgroundColor: '#e99b16',
            borderRadius: 5,
            borderSkipped: false,
            maxBarThickness: 20
          }]
        },
        options: {
          indexAxis: 'y',
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: { display: false },
            tooltip: {
              backgroundColor: '#ffffff',
              borderColor: '#e5e8ec',
              borderWidth: 1,
              titleColor: '#1a1d21',
              bodyColor: '#3f454d',
              padding: 10,
              cornerRadius: 8,
              displayColors: false
            }
          },
          scales: {
            x: {
              beginAtZero: true,
              grid: { color: '#eceff3' },
              border: { color: '#d4d8de' },
              ticks: { color: '#6b7078', precision: 0 }
            },
            y: {
              grid: { display: false },
              border: { color: '#d4d8de' },
              ticks: { color: '#3f454d', autoSkip: false, font: { size: 12 } }
            }
          }
        }
      });
    }
  }

  function renderCharts(rows) {
    var dimLabel = state.barDimension === 'location'
      ? 'Volume by Location'
      : (state.barDimension === 'branch' ? 'Volume by Branch' : 'Volume by Customer');
    var dimSub = state.barDimension === 'location'
      ? 'Order count per location in current scope'
      : (state.barDimension === 'branch' ? 'Order count per branch in current scope' : 'Order count per customer in current scope');
    setText('barTitle', dimLabel);
    setText('barSub', dimSub);
    var barData = buildBarData(rows, state.barDimension);
    setText('barMeta', rows.length ? barData.labels.length + ' segments' : '—');
    setChartEmpty('barEmpty', rows.length === 0);
    if (barChart) {
      var isOthers = function (label, idx) { return label === 'Others' && idx === barData.labels.length - 1; };
      var colors = barData.labels.map(function (_, idx) {
        return isOthers(barData.labels[idx], idx) ? 'rgba(94,106,210,0.45)' : '#5e6ad2';
      });
      var hoverColors = barData.labels.map(function (_, idx) {
        return isOthers(barData.labels[idx], idx) ? 'rgba(130,143,255,0.55)' : '#828fff';
      });
      barChart.data.labels = barData.labels;
      barChart.data.datasets[0].data = barData.data;
      barChart.data.datasets[0].backgroundColor = colors;
      barChart.data.datasets[0].hoverBackgroundColor = hoverColors;
      barChart.update();
    }

    var dData = buildDoughnutData(rows);
    setText('doughnutMeta', rows.length ? formatNum(dData.total) + ' records' : '—');
    setChartEmpty('doughnutEmpty', rows.length === 0);
    if (doughnutChart) {
      doughnutChart.data.datasets[0].data = dData.data;
      doughnutChart.options.plugins.centerText.total = dData.total;
      doughnutChart.update();
    }

    renderTrendChart(rows);
  }

  function renderTrendChart(rows) {
    var tData = buildTrendData(rows, state.trendGranularity);
    setText('trendMeta', rows.length ? formatNum(tData.labels.length) + ' periods' : '—');
    setChartEmpty('trendEmpty', rows.length === 0);
    if (!trendChart) return;
    trendChart.data.labels = tData.labels;
    trendChart.data.datasets[0].data = tData.orders;
    trendChart.data.datasets[1].data = tData.dispatched;
    trendChart.update();
  }

  /* -------------------------------------------------------------
     Backlog aging + data quality
     ------------------------------------------------------------- */
  function renderAging(rows) {
    var panel = $('backlogPanel');
    if (!panel) return;
    var list = $('backlogList');
    var aData = buildAgingData(rows);
    var has = aData.total > 0;
    setText('backlogMeta', has ? formatNum(aData.total) + ' open' : '0 open');
    setChartEmpty('agingEmpty', !has);
    if (agingChart) {
      agingChart.data.labels = aData.buckets.map(function (b) { return b.label; });
      agingChart.data.datasets[0].data = aData.buckets.map(function (b) { return b.count; });
      agingChart.update();
    }
    if (!list) return;
    if (!has) {
      list.innerHTML = '<p class="backlog-empty">No open P1 bottlenecks in current scope</p>';
      return;
    }
    var html = '';
    for (var i = 0; i < aData.oldest.length; i++) {
      var r = aData.oldest[i];
      var ageCls = r.age >= 15 ? ' is-old' : '';
      html +=
        '<div class="backlog-item">' +
        '<span class="bl-cust">' + escapeHtml(r.customer || '—') + '</span>' +
        '<span class="bl-meta">' + escapeHtml((r.branch || '—') + (r.location ? ' · ' + r.location : '')) + '</span>' +
        '<span class="bl-date">' + formatDate(r.orderDate) + '</span>' +
        '<span class="bl-age' + ageCls + '">' + formatNum(r.age) + 'd</span>' +
        '</div>';
    }
    list.innerHTML =
      '<div class="backlog-list-head"><span class="bl-title">Oldest open P1 bottlenecks</span>' +
      '<span class="mono">' + formatNum(aData.total) + ' total</span></div>' +
      html;
  }

  function renderRouteOverview(rows) {
    var tbody = $('routesBody');
    var meta = $('routesMeta');
    if (!tbody) return;
    var stats = buildRouteStats(rows);
    if (meta) meta.textContent = stats.length ? formatNum(stats.length) + ' routes' : 'No routes';
    if (!stats.length) {
      tbody.innerHTML = '<tr class="row-empty"><td colspan="7">No route data in current scope</td></tr>';
      return;
    }
    var html = '';
    for (var i = 0; i < stats.length; i++) {
      var s = stats[i];
      var active = state.route === s.route;
      var pct = Math.round(s.fulfillment);
      var pctCls = pct < 60 ? ' is-low' : (pct < 90 ? ' is-mid' : '');
      html +=
        '<tr class="route-row' + (active ? ' is-active' : '') + '" data-route="' + escapeHtml(s.route) + '" tabindex="0" aria-label="Filter to route ' + escapeHtml(s.route) + '">' +
        '<td class="td-strong"><span class="route-chip">' + escapeHtml(s.route) + '</span></td>' +
        '<td class="td-strong">' + formatNum(s.total) + '</td>' +
        '<td>' + (s.openP1 ? '<span class="badge badge-p1">' + formatNum(s.openP1) + '</span>' : '—') + '</td>' +
        '<td>' + formatNum(s.done) + '</td>' +
        '<td>' + formatNum(s.transit) + '</td>' +
        '<td>' + formatNum(s.pending) + '</td>' +
        '<td><span class="fulfillment"><span class="fulfillment-track"><span class="fulfillment-fill' + pctCls + '" style="width:' + Math.min(100, Math.max(0, pct)) + '%"></span></span><span class="fulfillment-num">' + pct + '%</span></span></td>' +
        '</tr>';
    }
    tbody.innerHTML = html;
  }

  function toggleRoute(r) {
    setRouteFilter(state.route === r ? 'ALL' : r);
  }

  function renderQuality(rows) {
    var meta = $('qualityMeta');
    var report = $('qualityReport');
    var empty = $('qualityEmpty');
    var issuesBox = $('qualityIssues');
    if (!meta || !report) return;
    var aData = auditData(rows);
    if (!aData.issues.length) {
      meta.textContent = 'No issues';
      meta.className = 'status-badge';
      if (empty) empty.hidden = false;
      if (issuesBox) issuesBox.innerHTML = '';
      return;
    }
    meta.textContent = aData.issues.reduce(function (s, c) { return s + c.count; }, 0) + ' flagged rows';
    meta.className = 'status-badge';
    if (empty) empty.hidden = true;
    if (!issuesBox) return;
    var html = '';
    for (var i = 0; i < aData.issues.length; i++) {
      var cat = aData.issues[i];
      html += '<div class="quality-cat">' +
        '<div class="quality-cat-head"><span class="qc-label">' + escapeHtml(cat.label) + '</span>' +
        '<span class="qc-count">' + formatNum(cat.count) + (cat.count > cat.rows.length ? ' · showing ' + cat.rows.length : '') + '</span></div>' +
        '<div class="table-wrap"><table class="quality-table">';
      for (var j = 0; j < cat.rows.length; j++) {
        var r = cat.rows[j];
        html += '<tr>' +
          '<td class="qc-strong">' + escapeHtml(r.customer || '—') + '</td>' +
          '<td>' + escapeHtml(r.branch || '—') + '</td>' +
          '<td>' + escapeHtml(r.location || '—') + '</td>' +
          '<td>' + formatDate(r.orderDate) + '</td>' +
          '<td>' + priorityBadge(r.priority) + '</td>' +
          '<td>' + formatDate(r.dispatchDate) + '</td>' +
          '</tr>';
      }
      html += '</table></div></div>';
    }
    issuesBox.innerHTML = html;
  }

  /* -------------------------------------------------------------
     Matrix table
     ------------------------------------------------------------- */
  function renderSortIcons() {
    var headers = document.querySelectorAll('th.sortable');
    for (var i = 0; i < headers.length; i++) {
      var th = headers[i];
      var ind = th.querySelector('.sort-ind');
      var active = th.getAttribute('data-key') === state.sortKey;
      th.classList.toggle('sorted', active);
      th.setAttribute('aria-sort', active ? (state.sortDir === 'asc' ? 'ascending' : 'descending') : 'none');
      if (ind) {
        ind.innerHTML = active
          ? '<i data-lucide="' + (state.sortDir === 'asc' ? 'chevron-up' : 'chevron-down') + '"></i>'
          : '<i data-lucide="chevrons-up-down"></i>';
      }
    }
    refreshIcons();
  }

  function renderTable() {
    var tbody = $('tableBody');
    if (!tbody) return;
    var rows = sortRows(filteredRows(), state.sortKey, state.sortDir);
    setText('rowCount', formatNum(rows.length) + ' of ' + formatNum(state.records.length) + ' records');
    if (!rows.length) {
      var msg = state.records.length
        ? 'No records match the current filters'
        : 'No data yet — drag & drop a file above, or sync the Google Sheet';
      tbody.innerHTML = '<tr class="row-empty"><td colspan="8">' + msg + '</td></tr>';
      return;
    }
    var html = '';
    for (var i = 0; i < rows.length; i++) {
      var r = rows[i];
      html +=
        '<tr>' +
        '<td class="td-date">' + formatDate(r.orderDate) + '</td>' +
        '<td class="td-strong">' + escapeHtml(r.customer || '—') + '</td>' +
        '<td>' + escapeHtml(r.branch || '—') + '</td>' +
        '<td>' + escapeHtml(r.location || '—') + '</td>' +
        '<td>' + escapeHtml(r.route || '—') + '</td>' +
        '<td>' + priorityBadge(r.priority) + '</td>' +
        '<td class="td-date">' + formatDate(r.dispatchDate) + '</td>' +
        '<td>' + ackBadge(r.ack) + '</td>' +
        '</tr>';
    }
    tbody.innerHTML = html;
  }

  /* -------------------------------------------------------------
     Source badge
     ------------------------------------------------------------- */
  function renderSource() {
    var el = $('dataSourceBadge');
    if (!el) return;
    if (!state.records.length) {
      el.textContent = 'No data loaded';
      el.removeAttribute('title');
      updateLastUpdated();
      return;
    }
    var label = state.source && state.source.name
      ? state.source.name + ' · ' + formatNum(state.records.length) + ' rows'
      : formatNum(state.records.length) + ' rows';
    el.textContent = label;
    if (state.source && state.source.syncedAt) {
      state.lastSyncAt = state.source.syncedAt;
      el.title = 'Loaded at ' + new Date(state.source.syncedAt).toLocaleString();
    } else {
      el.removeAttribute('title');
    }
    updateLastUpdated();
  }

  function updateLastUpdated() {
    var el = $('lastUpdated');
    var btn = $('autoRefreshBtn');
    if (el) {
      if (!state.lastSyncAt) {
        el.hidden = true;
      } else {
        el.hidden = false;
        var mins = Math.max(0, Math.floor((Date.now() - state.lastSyncAt) / 60000));
        el.textContent = mins < 1 ? 'Updated just now' : (mins < 60 ? 'Updated ' + mins + ' min ago' : 'Updated ' + formatNum(Math.floor(mins / 60)) + 'h ago');
      }
    }
    if (btn) {
      btn.hidden = !state.records.length;
      var label = $('autoRefreshLabel');
      if (label) label.textContent = state.autoRefresh ? 'Auto-refresh: On' : 'Auto-refresh: Off';
      btn.classList.toggle('is-on', state.autoRefresh);
    }
  }

  /* -------------------------------------------------------------
     Filters, search, sort
     ------------------------------------------------------------- */
  function renderAll() {
    var rows = filteredRows();
    renderIngestPanel();
    renderRouteFilter();
    renderKpis(rows);
    renderCharts(rows);
    renderTable();
    renderSource();
    renderCustomers();
    renderDirectoryMeta();
    renderAging(rows);
    renderRouteOverview(filteredRows(true));
    renderQuality(rows);
    refreshIcons();
  }

  function renderIngestPanel() {
    var hasData = state.records.length > 0 || state.customers.length > 0 || Object.keys(state.branches).length > 0;
    var panel = $('ingestPanel');
    if (panel) panel.hidden = hasData;
    var btn = $('showUploadBtn');
    if (btn) btn.hidden = !hasData;
  }

  /* -------------------------------------------------------------
     View tabs + customer directory
     ------------------------------------------------------------- */
  function setView(view) {
    state.view = view;
    var tabs = document.querySelectorAll('#viewTabs .tab');
    for (var i = 0; i < tabs.length; i++) {
      tabs[i].classList.toggle('is-active', tabs[i].getAttribute('data-view') === view);
    }
    var dv = $('dispatchView');
    if (dv) dv.hidden = view !== 'dispatch';
    var cv = $('customersView');
    if (cv) cv.hidden = view !== 'customers';
    refreshIcons();
  }

  function renderDirectoryMeta() {
    var meta = $('customerMeta');
    if (meta) {
      if (!state.customers.length) {
        meta.textContent = 'No master loaded';
        meta.removeAttribute('title');
      } else {
        meta.textContent = formatNum(state.customers.length) + ' customers';
        if (state.customersSource && state.customersSource.syncedAt) {
          meta.title = (state.customersSource.name || 'Master') + ' · loaded at ' +
            new Date(state.customersSource.syncedAt).toLocaleString();
        } else {
          meta.removeAttribute('title');
        }
      }
    }
    var bm = $('branchMeta');
    if (bm) {
      var count = Object.keys(state.branches).length;
      if (count) {
        bm.textContent = count + ' branch file' + (count === 1 ? '' : 's');
        bm.hidden = false;
      } else {
        bm.hidden = true;
      }
    }
  }

  function renderCustomers() {
    var tbody = $('customerBody');
    if (!tbody) return;
    if (!state.customers.length) {
      tbody.innerHTML = '<tr class="row-empty"><td colspan="8">No customer data yet — use "Upload / replace data" and drop the ALL_Customers master file, plus per-customer branch workbooks.</td></tr>';
      return;
    }
    var q = state.customerQuery.toLowerCase();
    var list = state.customers.filter(function (c) {
      if (!q) return true;
      return String(c.code).toLowerCase().indexOf(q) !== -1 ||
        String(c.name).toLowerCase().indexOf(q) !== -1 ||
        String(c.city).toLowerCase().indexOf(q) !== -1 ||
        String(c.state).toLowerCase().indexOf(q) !== -1 ||
        String(c.contact).toLowerCase().indexOf(q) !== -1;
    });
    list.sort(function (a, b) {
      return String(a.name).localeCompare(String(b.name), undefined, { numeric: true, sensitivity: 'base' });
    });
    var html = '';
    for (var i = 0; i < list.length; i++) {
      var c = list[i];
      var branches = state.branches[c.code] || [];
      var stats = customerOrderStats(c.name, state.records);
      var clickable = branches.length > 0;
      var aria = clickable ? ' role="button" tabindex="0" aria-label="View branches for ' + escapeHtml(c.name) + '"' : '';
      html +=
        '<tr class="cust-row' + (clickable ? ' is-clickable' : '') + '" data-code="' + escapeHtml(c.code) + '"' + aria + '>' +
        '<td class="td-mono">' + escapeHtml(c.code || '—') + '</td>' +
        '<td class="td-strong">' + escapeHtml(c.name || '—') + '</td>' +
        '<td>' + escapeHtml(c.city || '—') + '</td>' +
        '<td>' + escapeHtml(c.contact || '—') + (c.mobile ? '<span class="td-mono"><br>' + escapeHtml(c.mobile) + '</span>' : '') + '</td>' +
        '<td class="td-mono td-dim">' + escapeHtml(c.gst || '—') + '</td>' +
        '<td>' + (clickable
          ? '<span class="count-chip">' + branches.length + '</span>'
          : '<span class="count-chip is-muted">—</span>') + '</td>' +
        '<td class="td-mono">' + (stats.orders ? formatNum(stats.orders) : '<span class="pending-date">—</span>') + '</td>' +
        '<td class="td-mono ' + (stats.open ? 'cust-open' : 'cust-open is-zero') + '">' + formatNum(stats.open) + '</td>' +
        '</tr>';
    }
    if (!list.length) {
      tbody.innerHTML = '<tr class="row-empty"><td colspan="8">No customers match the current search.</td></tr>';
    } else {
      tbody.innerHTML = html;
    }
  }

  function renderBranches(code) {
    var drawer = $('branchDrawer');
    if (!drawer) return;
    var cust = null;
    for (var i = 0; i < state.customers.length; i++) {
      if (state.customers[i].code === code) { cust = state.customers[i]; break; }
    }
    var list = state.branches[code] || [];
    var title = $('drawerTitle');
    if (title) title.textContent = code + (cust && cust.name ? ' · ' + cust.name : '') + ' — Branches';
    var sub = $('drawerSub');
    if (sub) sub.textContent = formatNum(list.length) + ' branches';
    var body = $('branchBody');
    if (body) {
      if (!list.length) {
        body.innerHTML = '<tr class="row-empty"><td colspan="6">No branch file loaded for ' + escapeHtml(code) +
          ' — drop its branch workbook (e.g. ' + escapeHtml(code) + '.xlsx) into the upload zone.</td></tr>';
      } else {
        var html = '';
        for (var j = 0; j < list.length; j++) {
          var b = list[j];
          html +=
            '<tr>' +
            '<td class="td-strong">' + escapeHtml(b.branchName || '—') + '</td>' +
            '<td>' + escapeHtml(b.contact || '—') + '</td>' +
            '<td class="td-mono">' + escapeHtml(b.mobile || '—') + '</td>' +
            '<td>' + escapeHtml(b.address || '—') + '</td>' +
            '<td>' + escapeHtml(b.state || '—') + '</td>' +
            '<td class="td-mono">' + escapeHtml(b.pincode || '—') + '</td>' +
            '</tr>';
        }
        body.innerHTML = html;
      }
    }
    drawer.hidden = false;
    state.openCustomer = code;
    refreshIcons();
  }

  function renderRouteFilter() {
    var box = $('routeFilter');
    if (!box) return;
    var routes = {};
    state.records.forEach(function (r) { if (r.route) routes[r.route] = true; });
    var list = Object.keys(routes).sort(function (a, b) {
      return String(a).localeCompare(String(b), undefined, { numeric: true });
    });
    var html = '<button type="button" class="pill' + (state.route === 'ALL' ? ' is-active' : '') + '" data-route="ALL">All</button>';
    for (var i = 0; i < list.length; i++) {
      html += '<button type="button" class="pill' + (state.route === list[i] ? ' is-active' : '') + '" data-route="' + escapeHtml(list[i]) + '">' + escapeHtml(list[i]) + '</button>';
    }
    box.innerHTML = html;
  }

  function setRouteFilter(r) {
    state.route = r;
    renderAll();
  }

  function resetFilters(silent) {
    state.priority = 'ALL';
    state.ack = 'ALL';
    state.route = 'ALL';
    state.query = '';
    state.dateFrom = null;
    state.dateTo = null;
    var search = $('searchInput');
    if (search) search.value = '';
    var df = $('dateFrom');
    if (df) df.value = '';
    var dt = $('dateTo');
    if (dt) dt.value = '';
    var priorityPills = document.querySelectorAll('#priorityFilter .pill');
    for (var i = 0; i < priorityPills.length; i++) {
      priorityPills[i].classList.toggle('is-active', priorityPills[i].getAttribute('data-priority') === 'ALL');
    }
    var ackPills = document.querySelectorAll('#ackFilter .pill');
    for (var j = 0; j < ackPills.length; j++) {
      ackPills[j].classList.toggle('is-active', ackPills[j].getAttribute('data-ack') === 'ALL');
    }
    if (!silent) renderAll();
  }

  function setPriorityFilter(p) {
    state.priority = p;
    var pills = document.querySelectorAll('#priorityFilter .pill');
    for (var i = 0; i < pills.length; i++) {
      pills[i].classList.toggle('is-active', pills[i].getAttribute('data-priority') === p);
    }
    renderAll();
  }

  function setAckFilter(a) {
    state.ack = a;
    var pills = document.querySelectorAll('#ackFilter .pill');
    for (var i = 0; i < pills.length; i++) {
      pills[i].classList.toggle('is-active', pills[i].getAttribute('data-ack') === a);
    }
    renderAll();
  }

  function setBarDimension(d) {
    state.barDimension = d;
    var pills = document.querySelectorAll('#barDimension .pill');
    for (var i = 0; i < pills.length; i++) {
      pills[i].classList.toggle('is-active', pills[i].getAttribute('data-dim') === d);
    }
    renderAll();
  }

  function setTrendGranularity(g) {
    state.trendGranularity = g;
    var pills = document.querySelectorAll('#trendGranularity .pill');
    for (var i = 0; i < pills.length; i++) {
      pills[i].classList.toggle('is-active', pills[i].getAttribute('data-granularity') === g);
    }
    renderTrendChart(filteredRows());
  }

  function setAutoRefresh(on) {
    state.autoRefresh = !!on;
    try { localStorage.setItem(AUTO_REFRESH_KEY, state.autoRefresh ? '1' : '0'); } catch (e) {}
    if (state.autoRefresh) {
      if (autoRefreshTimer) clearInterval(autoRefreshTimer);
      autoRefreshTimer = setInterval(function () {
        if (!navigator.onLine) return;
        syncFromSheet();
      }, AUTO_REFRESH_MS);
    } else {
      if (autoRefreshTimer) { clearInterval(autoRefreshTimer); autoRefreshTimer = null; }
    }
    updateLastUpdated();
  }

  function startLastUpdatedTick() {
    if (lastUpdatedTick) clearInterval(lastUpdatedTick);
    lastUpdatedTick = setInterval(function () {
      updateLastUpdated();
      if (state.records.length) {
        renderAging(filteredRows());
        renderQuality(filteredRows());
      }
    }, 60000);
  }

  /* -------------------------------------------------------------
     Ingestion flows
     ------------------------------------------------------------- */
  function applyRecords(records, source) {
    enrichRoutes(records);
    state.records = records;
    state.source = source || null;
    resetFilters(true);
    renderAll();
    persistRecords(records, source).catch(function (e) {
      console.warn('Could not persist to IndexedDB:', e);
    });
  }

  function applyCustomers(list, source) {
    state.customers = list;
    state.customersSource = source || null;
    renderCustomers();
    renderDirectoryMeta();
    renderIngestPanel();
    persistCustomers(list, source).catch(function (e) {
      console.warn('Could not persist customers to IndexedDB:', e);
    });
  }

  function applyBranches(code, list, source) {
    if (!code) return;
    state.branches[code] = list;
    state.branchesSource = source || null;
    renderCustomers();
    renderDirectoryMeta();
    if (state.openCustomer === code) renderBranches(code);
    persistBranches(state.branches, source).catch(function (e) {
      console.warn('Could not persist branches to IndexedDB:', e);
    });
  }

  function handleFiles(fileList) {
    var files = Array.prototype.slice.call(fileList || []);
    files.forEach(function (file) {
      if (!file) return;
      var ext = (file.name.split('.').pop() || '').toLowerCase();
      if (['xlsx', 'xls', 'csv'].indexOf(ext) === -1 && file.type !== 'text/csv') {
        showError('"' + file.name + '" is not a supported workbook. Please upload .xlsx, .xls or .csv.');
        return;
      }
      processFile(file);
    });
  }

  function processFile(file) {
    var title = $('dzTitle');
    var originalTitle = title ? title.textContent : '';
    if (title) title.textContent = 'Processing ' + file.name + '…';

    var reader = new FileReader();
    reader.onload = function (e) {
      try {
        if (typeof XLSX === 'undefined') throw new Error('SheetJS failed to load — check your internet connection.');
        var wb = XLSX.read(new Uint8Array(e.target.result), { type: 'array' });
        var rows = [];
        for (var i = 0; i < wb.SheetNames.length; i++) {
          var sheet = wb.Sheets[wb.SheetNames[i]];
          if (!sheet || !sheet['!ref']) continue;
          rows = rows.concat(XLSX.utils.sheet_to_json(sheet, { header: 1, defval: '', raw: true }));
        }
        var kind = classifyWorkbook(rows);
        if (kind === 'customers') {
          var custs = parseCustomerMaster(rows);
          if (!custs.length) throw new Error('No customer rows found in ' + file.name + '.');
          applyCustomers(custs, { name: file.name, syncedAt: Date.now() });
          toast('Loaded ' + formatNum(custs.length) + ' customers from ' + file.name, 'success');
        } else if (kind === 'branches') {
          var code = codeFromFilename(file.name);
          var branches = parseBranchList(rows);
          if (!branches.length) throw new Error('No branch rows found in ' + file.name + '.');
          applyBranches(code, branches, { name: file.name, syncedAt: Date.now() });
          toast('Loaded ' + formatNum(branches.length) + ' branches for ' + code + ' from ' + file.name, 'success');
        } else {
          var result = ingestWorkbook(wb);
          if (result.missing.length) {
            throw new Error('Required columns missing: ' + result.missing.join(', ') + '. Expected: ' + REQUIRED_COLUMNS.join(', '));
          }
          if (!result.records.length) throw new Error('No data rows found in ' + file.name + '.');
          applyRecords(result.records, { name: file.name, syncedAt: Date.now() });
          toast('Imported ' + formatNum(result.records.length) + ' rows from ' + file.name, 'success');
        }
      } catch (err) {
        showError(err.message || 'Failed to parse the uploaded file.');
      } finally {
        if (title && originalTitle) title.textContent = originalTitle;
        var input = $('fileInput');
        if (input) input.value = '';
      }
    };
    reader.onerror = function () {
      showError('Could not read the selected file.');
      if (title && originalTitle) title.textContent = originalTitle;
      var input = $('fileInput');
      if (input) input.value = '';
    };
    reader.readAsArrayBuffer(file);
  }

  function handleFile(file) {
    handleFiles([file]);
  }

  function setSyncing(on) {
    var ids = ['syncBtn', 'syncBtn2'];
    for (var i = 0; i < ids.length; i++) {
      var btn = $(ids[i]);
      if (!btn) continue;
      var icon = btn.querySelector('svg, i');
      if (on) {
        btn.disabled = true;
        if (icon) icon.classList.add('spin');
      } else {
        btn.disabled = false;
        if (icon) icon.classList.remove('spin');
      }
    }
    setText('syncBtn2Label', on ? 'Syncing…' : 'Pull live from Google Sheet');
  }

  async function syncFromSheet() {
    if (syncing) return;
    syncing = true;
    setSyncing(true);
    try {
      var records;
      var via = 'csv';
      try {
        var res = await fetch(SHEET_CSV_URL);
        if (!res.ok) throw new Error('HTTP ' + res.status);
        var csv = await res.text();
        var wb = XLSX.read(csv, { type: 'string' });
        var result = ingestWorkbook(wb);
        if (result.missing.length) throw new Error('Sheet columns not recognised: ' + result.missing.join(', '));
        if (!result.records.length) throw new Error('Sheet contains no data rows.');
        records = result.records;
      } catch (csvErr) {
        via = 'gviz';
        var gRes = await fetch(SHEET_GVIZ_URL);
        if (!gRes.ok) throw new Error('HTTP ' + gRes.status);
        var raw = parseGvizRows(await gRes.text());
        records = raw.map(normalizeRecord);
      }
      if (!records.length) throw new Error('Sheet contains no usable rows.');
      applyRecords(records, { name: 'Live Google Sheet', syncedAt: Date.now(), via: via });
      toast('Synced ' + formatNum(records.length) + ' rows from Google Sheet', 'success');
    } catch (err) {
      if (isFileProtocol()) showLocalNotice();
      showError('Google Sheet sync failed — ' + describeSyncError(err));
    } finally {
      setSyncing(false);
      syncing = false;
    }
  }

  /* -------------------------------------------------------------
     Events + init
     ------------------------------------------------------------- */
  function wireEvents() {
    var dz = $('dropzone');
    var fileInput = $('fileInput');
    var pickBtn = $('pickBtn');

    if (dz && fileInput) {
      dz.addEventListener('click', function (e) {
        if (e.target.closest && e.target.closest('button')) return;
        fileInput.click();
      });
      dz.addEventListener('keydown', function (e) {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          fileInput.click();
        }
      });
      ['dragenter', 'dragover'].forEach(function (ev) {
        dz.addEventListener(ev, function (e) {
          e.preventDefault();
          e.stopPropagation();
          dz.classList.add('is-dragover');
        });
      });
      ['dragleave', 'drop'].forEach(function (ev) {
        dz.addEventListener(ev, function (e) {
          e.preventDefault();
          e.stopPropagation();
          dz.classList.remove('is-dragover');
        });
      });
      dz.addEventListener('drop', function (e) {
        var files = e.dataTransfer && e.dataTransfer.files;
        if (files && files.length) handleFiles(files);
      });
    }

    if (pickBtn && fileInput) {
      pickBtn.addEventListener('click', function () { fileInput.click(); });
    }
    if (fileInput) {
      fileInput.addEventListener('change', function () {
        if (fileInput.files && fileInput.files.length) handleFiles(fileInput.files);
      });
    }

    var syncBtn = $('syncBtn');
    var syncBtn2 = $('syncBtn2');
    if (syncBtn) syncBtn.addEventListener('click', syncFromSheet);
    if (syncBtn2) syncBtn2.addEventListener('click', syncFromSheet);

    var priorityPills = document.querySelectorAll('#priorityFilter .pill');
    for (var i = 0; i < priorityPills.length; i++) {
      priorityPills[i].addEventListener('click', function (ev) {
        setPriorityFilter(ev.currentTarget.getAttribute('data-priority'));
      });
    }
    var ackPills = document.querySelectorAll('#ackFilter .pill');
    for (var j = 0; j < ackPills.length; j++) {
      ackPills[j].addEventListener('click', function (ev) {
        setAckFilter(ev.currentTarget.getAttribute('data-ack'));
      });
    }
    var routeFilter = $('routeFilter');
    if (routeFilter) {
      routeFilter.addEventListener('click', function (ev) {
        var btn = ev.target.closest && ev.target.closest('.pill');
        if (btn && btn.getAttribute('data-route')) setRouteFilter(btn.getAttribute('data-route'));
      });
    }

    var routesBody = $('routesBody');
    if (routesBody) {
      routesBody.addEventListener('click', function (ev) {
        var row = ev.target.closest && ev.target.closest('tr.route-row');
        if (row && row.getAttribute('data-route')) toggleRoute(row.getAttribute('data-route'));
      });
      routesBody.addEventListener('keydown', function (ev) {
        if (ev.key === 'Enter' || ev.key === ' ') {
          var row = ev.target.closest && ev.target.closest('tr.route-row');
          if (row && row.getAttribute('data-route')) {
            ev.preventDefault();
            toggleRoute(row.getAttribute('data-route'));
          }
        }
      });
    }
    var resetBtn = $('resetFilters');
    if (resetBtn) resetBtn.addEventListener('click', function () { resetFilters(false); });

    var dateFrom = $('dateFrom');
    var dateTo = $('dateTo');
    if (dateFrom) {
      dateFrom.addEventListener('change', function () {
        state.dateFrom = dateFrom.value ? new Date(dateFrom.value + 'T00:00:00') : null;
        renderAll();
      });
    }
    if (dateTo) {
      dateTo.addEventListener('change', function () {
        state.dateTo = dateTo.value ? new Date(dateTo.value + 'T00:00:00') : null;
        renderAll();
      });
    }

    var dimPills = document.querySelectorAll('#barDimension .pill');
    for (var d = 0; d < dimPills.length; d++) {
      dimPills[d].addEventListener('click', function (ev) {
        setBarDimension(ev.currentTarget.getAttribute('data-dim'));
      });
    }

    var granPills = document.querySelectorAll('#trendGranularity .pill');
    for (var gr = 0; gr < granPills.length; gr++) {
      granPills[gr].addEventListener('click', function (ev) {
        setTrendGranularity(ev.currentTarget.getAttribute('data-granularity'));
      });
    }

    var autoRefreshBtn = $('autoRefreshBtn');
    if (autoRefreshBtn) {
      autoRefreshBtn.addEventListener('click', function () {
        setAutoRefresh(!state.autoRefresh);
        if (state.autoRefresh && state.records.length) syncFromSheet();
      });
    }

    var qualityToggle = $('qualityToggle');
    if (qualityToggle) {
      qualityToggle.addEventListener('click', function () {
        var report = $('qualityReport');
        var label = $('qualityToggleLabel');
        if (!report) return;
        var open = report.hidden;
        report.hidden = !open;
        var icon = qualityToggle.querySelector('i');
        if (icon) icon.setAttribute('data-lucide', open ? 'chevron-up' : 'chevron-down');
        if (label) label.textContent = open ? 'Hide report' : 'Show report';
        refreshIcons();
      });
    }

    var showUploadBtn = $('showUploadBtn');
    if (showUploadBtn) {
      showUploadBtn.addEventListener('click', function () {
        var panel = $('ingestPanel');
        if (panel) panel.hidden = false;
        showUploadBtn.hidden = true;
        if (panel && panel.scrollIntoView) panel.scrollIntoView({ behavior: 'smooth', block: 'start' });
        var input = $('fileInput');
        if (input) input.focus();
      });
    }

    var tabs = document.querySelectorAll('#viewTabs .tab');
    for (var t = 0; t < tabs.length; t++) {
      tabs[t].addEventListener('click', function (ev) {
        setView(ev.currentTarget.getAttribute('data-view'));
      });
    }

    var customerSearch = $('customerSearch');
    if (customerSearch) {
      var cDebounce = null;
      customerSearch.addEventListener('input', function () {
        clearTimeout(cDebounce);
        cDebounce = setTimeout(function () {
          state.customerQuery = customerSearch.value.trim();
          renderCustomers();
        }, 140);
      });
    }

    var customerBody = $('customerBody');
    if (customerBody) {
      customerBody.addEventListener('click', function (ev) {
        var row = ev.target.closest && ev.target.closest('tr.cust-row');
        if (row && row.getAttribute('data-code')) {
          renderBranches(row.getAttribute('data-code'));
        }
      });
      customerBody.addEventListener('keydown', function (ev) {
        if (ev.key === 'Enter' || ev.key === ' ') {
          var row = ev.target.closest && ev.target.closest('tr.cust-row');
          if (row && row.getAttribute('data-code')) {
            ev.preventDefault();
            renderBranches(row.getAttribute('data-code'));
          }
        }
      });
    }

    var drawerClose = $('drawerClose');
    if (drawerClose) {
      drawerClose.addEventListener('click', function () {
        var drawer = $('branchDrawer');
        if (drawer) drawer.hidden = true;
        state.openCustomer = null;
      });
    }

    var search = $('searchInput');
    if (search) {
      var debounce = null;
      search.addEventListener('input', function () {
        clearTimeout(debounce);
        debounce = setTimeout(function () {
          state.query = search.value.trim();
          renderAll();
        }, 140);
      });
    }

    var sortHeaders = document.querySelectorAll('th.sortable');
    for (var k = 0; k < sortHeaders.length; k++) {
      sortHeaders[k].addEventListener('click', function (ev) {
        var key = ev.currentTarget.getAttribute('data-key');
        if (state.sortKey === key) {
          state.sortDir = state.sortDir === 'asc' ? 'desc' : 'asc';
        } else {
          state.sortKey = key;
          state.sortDir = (key === 'orderDate' || key === 'dispatchDate') ? 'desc' : 'asc';
        }
        renderTable();
        renderSortIcons();
      });
    }
  }

  async function init() {
    refreshIcons();
    wireEvents();
    createCharts();
    renderSortIcons();
    startLastUpdatedTick();
    if (isFileProtocol()) showLocalNotice();

    try {
      var pref = localStorage.getItem(AUTO_REFRESH_KEY);
      state.autoRefresh = pref === '1';
    } catch (e) { state.autoRefresh = false; }

    try {
      db = await openDB();
    } catch (e) {
      db = null;
      console.warn('IndexedDB unavailable:', e);
    }

    var cached = await loadPersisted();
    if (cached) {
      if (cached.records && cached.records.length) {
        state.records = cached.records;
        state.source = cached.meta && cached.meta.name ? { name: cached.meta.name, syncedAt: cached.meta.syncedAt } : null;
        toast('Restored ' + formatNum(state.records.length) + ' rows from local cache', 'info');
      }
      if (cached.customers && cached.customers.length) {
        state.customers = cached.customers;
        state.customersSource = cached.customersMeta && cached.customersMeta.name
          ? { name: cached.customersMeta.name, syncedAt: cached.customersMeta.syncedAt } : null;
      }
      if (cached.branches && cached.branches.length) {
        cached.branches.forEach(function (entry) {
          if (entry && entry.code) state.branches[entry.code] = entry.list || [];
        });
        state.branchesSource = cached.branchesMeta && cached.branchesMeta.name
          ? { name: cached.branchesMeta.name, syncedAt: cached.branchesMeta.syncedAt } : null;
      }
    }
    renderAll();
    setView(state.view);

    await loadRouteMap();

    if (state.autoRefresh) {
      setAutoRefresh(true);
      if (state.records.length && navigator.onLine && !isFileProtocol()) syncFromSheet();
    }
  }

  async function loadRouteMap() {
    try {
      var res = await fetch(GHMC_MAP_URL);
      if (!res.ok) throw new Error('HTTP ' + res.status);
      var data = await res.json();
      routeMap = buildRouteIndex(data.records || []);
      var hadRoute = 0;
      for (var i = 0; i < state.records.length; i++) if (state.records[i].route) hadRoute++;
      enrichRoutes(state.records, routeMap);
      renderAll();
      var withRoute = 0;
      for (var j = 0; j < state.records.length; j++) if (state.records[j].route) withRoute++;
      if (withRoute > hadRoute) {
        toast('Auto-routed ' + (withRoute - hadRoute) + ' orders from Branch (GHMC map)', 'info');
      }
    } catch (e) {
      console.warn('GHMC route map unavailable (' + GHMC_MAP_URL + '):', e);
    }
  }

  /* Expose pure core for debugging + tests */
  window.DashboardCore = {
    REQUIRED_COLUMNS: REQUIRED_COLUMNS,
    HEADER_ALIASES: HEADER_ALIASES,
    PLACE_TYPO_MAP: PLACE_TYPO_MAP,
    cleanPlace: cleanPlace,
    cleanCustomer: cleanCustomer,
    normalizePriority: normalizePriority,
    normalizeAck: normalizeAck,
    parseDate: parseDate,
    normalizeRecord: normalizeRecord,
    detectHeaders: detectHeaders,
    buildRecords: buildRecords,
    ingestWorkbook: ingestWorkbook,
    parseGvizRows: parseGvizRows,
    classifyWorkbook: classifyWorkbook,
    codeFromFilename: codeFromFilename,
    parseCustomerMaster: parseCustomerMaster,
    parseBranchList: parseBranchList,
    computeKpis: computeKpis,
    buildBarData: buildBarData,
    buildDoughnutData: buildDoughnutData,
    buildTrendData: buildTrendData,
    buildAgingData: buildAgingData,
    buildRouteStats: buildRouteStats,
    auditData: auditData,
    customerOrderStats: customerOrderStats,
    sortRows: sortRows,
    filteredRows: filteredRows,
    buildRouteIndex: buildRouteIndex,
    routeFromBranch: routeFromBranch,
    enrichRoutes: enrichRoutes
  };

  init();
})();
